[2021-11-16 11:57:16,166] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: ml_pipeline.get_data scheduled__2021-11-15T00:18:00+00:00 [queued]>
[2021-11-16 11:57:16,174] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: ml_pipeline.get_data scheduled__2021-11-15T00:18:00+00:00 [queued]>
[2021-11-16 11:57:16,175] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-11-16 11:57:16,175] {taskinstance.py:1242} INFO - Starting attempt 1 of 2
[2021-11-16 11:57:16,175] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-11-16 11:57:16,248] {taskinstance.py:1262} INFO - Executing <Task(BashOperator): get_data> on 2021-11-15 00:18:00+00:00
[2021-11-16 11:57:16,250] {standard_task_runner.py:52} INFO - Started process 13569 to run task
[2021-11-16 11:57:16,255] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'ml_pipeline', 'get_data', 'scheduled__2021-11-15T00:18:00+00:00', '--job-id', '28', '--raw', '--subdir', 'DAGS_FOLDER/ml_dag.py', '--cfg-path', '/tmp/tmpr0zplv9x', '--error-file', '/tmp/tmprc0m7_14']
[2021-11-16 11:57:16,256] {standard_task_runner.py:77} INFO - Job 28: Subtask get_data
[2021-11-16 11:57:16,435] {logging_mixin.py:109} INFO - Running <TaskInstance: ml_pipeline.get_data scheduled__2021-11-15T00:18:00+00:00 [running]> on host ana-X550CA
[2021-11-16 11:57:16,594] {taskinstance.py:1427} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=plbalmeida
AIRFLOW_CTX_DAG_ID=ml_pipeline
AIRFLOW_CTX_TASK_ID=get_data
AIRFLOW_CTX_EXECUTION_DATE=2021-11-15T00:18:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-11-15T00:18:00+00:00
[2021-11-16 11:57:16,595] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2021-11-16 11:57:16,596] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'python3 /home/ana/Documentos/airflowML/src/data/make_dataset.py']
[2021-11-16 11:57:16,604] {subprocess.py:85} INFO - Output:
[2021-11-16 11:57:17,147] {subprocess.py:93} INFO - Command exited with return code 0
[2021-11-16 11:57:17,238] {taskinstance.py:1270} INFO - Marking task as SUCCESS. dag_id=ml_pipeline, task_id=get_data, execution_date=20211115T001800, start_date=20211116T145716, end_date=20211116T145717
[2021-11-16 11:57:17,350] {local_task_job.py:154} INFO - Task exited with return code 0
[2021-11-16 11:57:17,442] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
